### ISSUE TITLE
doesn't run

### ISSUE THREAD

**Issue by aeosynth** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#16]
First time trying this, the following script creates `test.mp4.ffindex` then ends, no error message:

```
import vapoursynth as vs
core = vs.core
clip = core.ffms2.Source(source='test.mp4')

clip = core.resize.Bicubic(clip, format=vs.RGBS, matrix_in_s='709')
clip = core.rife.RIFE(clip)
print('not reached')
```

using Arch Linux, following the compilation instructions. using `list_gpu` doesn't work either, the plain cli works.

**Comment by HolyWu** [comment]
You need to add `clip.set_output()` to the last line of your script for it to actually output the clip.

**Comment by aeosynth** [comment]
that doesn't work either, no code is reached after the line with `core.rife.RIFE`

**Comment by HolyWu** [comment]
Did you use vspipe to evaluate your script?

**Comment by aeosynth** [comment]
I used `python vs.py`. Using vspipe gives `pipe:: Invalid data found when processing input`

**Comment by HolyWu** [comment]
What's the entire command line of vspipe you used?

**Comment by aeosynth** [comment]
vs.py:

```
import vapoursynth as vs
core = vs.core
clip = core.ffms2.Source(source='test.mp4')

clip = core.resize.Bicubic(clip, format=vs.RGBS, matrix_in_s='709')
clip = core.rife.RIFE(clip)
clip = core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s='709')
clip.set_output()
```
```
[james@arch foo]$ vspipe -c y4m vs.py - | ffmpeg -i pipe: rife.mp4
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
pipe:: Invalid data found when processing input
```

**Comment by HolyWu** [comment]
Please try only `vspipe -p vs.py .` first to see whether it actually outputs.

**Comment by aeosynth** [comment]
rebuilt, no change

**Comment by HolyWu** [comment]
And does vspipe run successfully if you comment out that RIFE line from your script?

**Comment by aeosynth** [comment]
the previous release works: 1165ee2c26d11e88f508647096fd8d3bf6a74f18

```
[james@arch foo]$ vspipe -p vs.py .
[0 AMD RADV RENOIR]  queueC=1[4]  queueG=0[1]  queueT=0[1]
[0 AMD RADV RENOIR]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD RADV RENOIR]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD RADV RENOIR]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
Script evaluation done in 0.54 seconds
Frame: 59/22826 (6.04 fps)
```

**Comment by HolyWu** [comment]
Please try the latest commit. If it doesn't work, then I have no clue what's the culprit.

**Comment by aeosynth** [comment]
no luck. thanks for looking into this though

**Comment by styler00dollar** [comment]
Can confirm that I also have `pipe:: Invalid data found when processing input` and `Illegal instruction (core dumped)`. Cloning from the mentioned commit or using `meson build -Dbuildtype=debug -Db_lto=false` sadly didn't change the result.

**Comment by HolyWu** [comment]
What's your O.S., CPU, and GPU? I'm wondering whether the issue is specific to certain O.S. or hardward because I cannot reproduce it and so far no Windows user has reported the same problem.

**Comment by aeosynth** [comment]
arch, amd 5600g apu

**Comment by styler00dollar** [comment]
2700x, 1070ti. I can share my docker image so you can have the same software environment I had, but running the container with a GPU will only work with nvidia gpus.
```
yay -S docker nvidia-docker nvidia-container-toolkit docker-compose
docker pull styler00dollar/vsgan_tensorrt_dev:latest
docker run --privileged --gpus all -it --rm -v /home/mount_external_folder_path/:/workspace/your_mount_path/ styler00dollar/vsgan_tensorrt_dev:latest
```

Inside [Dockerfile_dev](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/main/Dockerfile_dev) you can also see how I tried to compile.
```
# rife ncnn
RUN git clone https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan && cd VapourSynth-RIFE-ncnn-Vulkan && \
    git submodule update --init --recursive --depth 1 && meson build -Dbuildtype=debug -Db_lto=false && ninja -C build && ninja -C build install && \
    cd /workspace && rm -rf VapourSynth-RIFE-ncnn-Vulkan
```
Inside the docker (after running docker dev) you can run cli like usual, install and uninstall stuff (will revert to defaults from dockerfile once you close) and run stuff like vspipe. Oddly enough, my own rife ncnn with python did work in that container which is located [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/main/src/rife.py) and [here](https://github.com/styler00dollar/rife-ncnn-vulkan-python), but I wonder if this repository is faster since it doesn't use python. One thing I didn't try yet was to directly try it on arch, but I would like to add it to docker since i have [this repo](https://github.com/styler00dollar/VSGAN-tensorrt-docker).

**Comment by HolyWu** [comment]
Please try to rebuild from https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/tree/test.

**Comment by styler00dollar** [comment]
I think it works now because recompiled with this `test` branch. :D Amazing.

**Comment by HolyWu** [comment]
I need to find out whether it's caused by the x86 optimizations or incompatible compiler flags. Please rebuild again if you have spare time, thanks.

**Comment by styler00dollar** [comment]
I will rebuild it later, probably tomorrow.

**Comment by waptaff** [comment]
I have the same issues as @styler00dollar on a Gentoo Linux with AMD GPU and AMD CPU.

Very latest commit on branch `test` (commit 14d30d609106e198ca5608d78f8ba1d196628ceb) fails with illegal instruction.

Penultimate commit on branch `test` (commit 95a6cda9b3df960d8d76fdcfcdabcff0a8df6771) does _not_ fail.


The illegal instruction happens for me in `ncnn/src/gpu.cpp` at line 1305, 

```
0x00007ffff5391d6e <+2798>:  vpxor  %xmm0,%xmm0,%xmm0
0x00007ffff5391d72 <+2802>:  vmovdqu %xmm0,0x3fc(%r14)
```

So it appears at some point in the build chain the CPU flag detection is wrong, as my CPU does not have AVX512 instructions.

**Comment by HolyWu** [comment]
Thank you for testing. If https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/commit/5863a29042c84af3dc7ea0be84b45c40e1e302f0 also works then the culprit is ineed AVX512.

**Comment by styler00dollar** [comment]
I tested the last few commits:
5863a29042c84af3dc7ea0be84b45c40e1e302f0 Works.
14d30d609106e198ca5608d78f8ba1d196628ceb Does not work.
95a6cda9b3df960d8d76fdcfcdabcff0a8df6771 Works.

**Comment by waptaff** [comment]
I confirm commit 5863a29042c84af3dc7ea0be84b45c40e1e302f0 works for me too.
