### ISSUE TITLE
"resulting clip is too long" while using the filter in mpv

### ISSUE THREAD

**Issue by chainikdn** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#17]
... cause mpv (as the other Vapoursynth-enabled video players) doesn't know the exact number of frames and set it to [INT_MAX/16 ](https://github.com/mpv-player/mpv/blob/305332f8a06e174c5c45c9c4547293502ac7ecdb/video/filter/vf_vapoursynth.c#L454)

why not remove this? or just limit multiplier to some big enough value instead
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/blob/d66004fd4bc2bf8a7e8f7d5629a496a63ad317bc/RIFE/plugin.cpp#L188

**Comment by HolyWu** [comment]
It's a sanity check to make sure `numFrames` doesn't overflow and become a negative value. How come I should remove it?

**Comment by chainikdn** [comment]
```
if (d->vi.numFrames > INT_MAX / d->multiplier)
            d->vi.numFrames = INT_MAX;
else d->vi.numFrames *= d->multiplier;
```
something like this, I suppose...
