### ISSUE TITLE
cannot load RIFE.dll

### ISSUE THREAD

**Issue by 1000thSummer** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#19]
failed to load it in vpy with following error logs
```
>>> core.std.LoadPlugin(".\\vapoursynth64\\plugins\\libmvtools.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2723, in vapoursynth.Function.__call__
vapoursynth.Error: Plugin .\vapoursynth64\plugins\libmvtools.dll already loaded (com.nodame.mvtools) from D:/Programs/mpvnet/vapoursynth64/plugins/libmvtools.dll
>>> core.std.LoadPlugin(".\\vapoursynth64\\plugins\\RIFE.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src\cython\vapoursynth.pyx", line 2723, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load .\vapoursynth64\plugins\RIFE.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```

Note that `libmvtools.dll` can be loaded successfully...

**Comment by HolyWu** [comment]
The plugin depends on Vulkan runtime library. Usually it's installed together with the GPU driver, unless your GPU is too old to support Vulkan...

**Comment by 1000thSummer** [comment]
Thanks for the quick reply.
I am using WHQL driver which got installed automatically -- not sure if vulkan comes with WHQL though.
I will try to install Vulkan manually then.

**Comment by 1000thSummer** [comment]
Tried to install vulkan and verified its existence in `C:/windows/system32/vulkan-1.dll`

Still failed to load RIFE.dll with same error
