### ISSUE TITLE
Feature request: floating point multiplier support for rife 4.0

### ISSUE THREAD

**Issue by elexor** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#20]
Hi

Floating point multipliers seem to work well enough and can be useful for turning 24fps into 60fps 2.5x

I have compiled my own build with fractional working but I don't have confidence in my programming ability to do it correctly.

Scene detection still functions just fine with floats.

**Comment by HolyWu** [comment]
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/commit/dcff4090f065e10ff60b681704b62ce8c8c7df4a

**Comment by elexor** [comment]
thankyou very much for doing this, I appreciate it!
