### ISSUE TITLE
Is this filter designed for realtime use?

### ISSUE THREAD

**Issue by Usulyre** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#3]
Hi, I am trying to use this filter for realtime use and video playback. I am using this as well (vapoursynth directshow filter) 

https://github.com/CrendKing/avisynth_filter

Here is my script:  

import vapoursynth as vs
core = vs.get_core()

clip = VpsFilterSource
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="full")
clip = core.rife.RIFE(clip, model=1, gpu_id=0, list_gpu=True, gpu_thread=4, tta=True, uhd=False, sc=False, fp32=True)
output_clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P8, matrix_s="709")
output_clip.set_output()

**Comment by Usulyre** [comment]
Questions:

Is this filter for realtime use like video playback?

If list_gpu=True is enabled, does the filter still work?

If I disable list_gpu, video playback becomes very slow and choppy?

Could you provide any fixes in my script to get interpolation to work?

Does your filter only double framerate?

**Comment by YiWeiHuang-stack** [comment]
This is an AI frame interpolation algorithm, and currently cannot achieve the speed of real-time frame interpolation
https://github.com/hzwer/arXiv2020-RIFE

**Comment by HolyWu** [comment]
> Is this filter for realtime use like video playback?

Probably no.

> If list_gpu=True is enabled, does the filter still work?

It only prints the list on the frame and does no interpolation.

> Does your filter only double framerate?

Yes, like what [rife-ncnn-vulkan](https://github.com/nihui/rife-ncnn-vulkan) does.
