### ISSUE TITLE
Is it possible to interpolate with alpha?

### ISSUE THREAD

**Issue by n00mkrad** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#33]
RIFE-NCNN supports alpha interpolation.

However, it seems like I can't use vspipe for this, as it can only do y4m, which does not support alpha.

Is there any workaround for this? I would like to pipe YUVA444 or RGB24 but it doesn't seem to work.

**Comment by HolyWu** [comment]
> RIFE-NCNN supports alpha interpolation.

ARE YOU SURE? There is no special codes dealing with alpha channel in https://github.com/nihui/rife-ncnn-vulkan/blob/master/src/rife.cpp and https://github.com/nihui/rife-ncnn-vulkan/blob/69aa101c2cc5c9f0d818c6b8bc2a6e469f89066a/src/rife.cpp#L397 is hardcoded as 3. Also https://github.com/nihui/rife-ncnn-vulkan/issues/14 still remains open.

**Comment by n00mkrad** [comment]
Ah my bad, I confused it with the Pytorch implementation which does support 4 channels.
