### ISSUE TITLE
r7 would make player crash when using the vs-filter in mpv

### ISSUE THREAD

**Issue by hooke007** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#35]
RIFE r6 works fine.

Vapoursynth R59+Python3.10.5

Here is the test.vpy

```python
import vapoursynth as vs
from vapoursynth import core

clip = video_in

clip = clip.resize.Bilinear(format=vs.RGBS, matrix_in_s="709")

#clip = core.rife.RIFE(clip=clip, model=9, multiplier=2)
#R6 —— No crash

clip = core.rife.RIFE(clip=clip, model=9, fps_num=48, fps_den=1)
#R7

clip = clip.resize.Bilinear(format=vs.YUV420P8, matrix_s="709")

clip.set_output()
```

**Comment by HolyWu** [comment]
Can you preview your script with vsedit or vspreview first?

**Comment by hooke007** [comment]
No issue in vsedit.

**Comment by krakow10** [comment]
Mine is also crashing in mpv.  It says "Floating point exception (core dumped)"

I found this using gdb, is this just a divide by zero exception?
![Screenshot_2022-08-01_11-55-55](https://user-images.githubusercontent.com/3529698/182223013-b6b4c03c-3693-4991-a526-82ad2e65b1f6.png)
Using `bt full` on gdb, it looks like it's called from right here:
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/blob/master/RIFE/plugin.cpp#L219

**Comment by Natural-Harmonia-Gropius** [comment]
The crash happens with VFR videos, that MPV always sends clip as VFR.
This issue could be fixed by `AssumeFPS`, However `AssumeFPS` make those real VFR videos dysnc.

**Comment by Natural-Harmonia-Gropius** [comment]
r8 throwing this.

https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan/blob/045de7288941e3c07427804d0737c9536fa3a56b/RIFE/plugin.cpp#L216

**Comment by HolyWu** [comment]
That's the reason why I added `factor_num` and `factor_den` parameters.

**Comment by krakow10** [comment]
I am able to use factor_num and factor_den with mpv now.
