### ISSUE TITLE
Example of usage with mpv?

### ISSUE THREAD

**Issue by sofakng** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#5]
Can you provide an example script (or documentation) of how to use this filter with mpv?

(I've already configured mpv with vapoursynth and it's working, but I'm unsure how to use this filter)

EDIT:  I think I've figured it out but the current release only supports 32-bit.  Can you compile a build of the latest version that supports 8-bit for me to test?

**Comment by HolyWu** [comment]
The algorithm is not fast enough for playback, so you probably wanna go with SVP. Anyway I will have another CUDA version which is 3 times faster than Vulkan.

**Comment by sofakng** [comment]
OK ... I'd still be interested in giving it a test if you would be able to provide a binary.

It looks like SVP also has a RIFE implementation and also mentions it's slow but says it should work up to 720p videos.

I will also look forward to your CUDA version!

**Comment by hooke007** [comment]
>SVP also has a RIFE implementation

No diff. Same files with this repo.
