### ISSUE TITLE
process resolution for optical flow model ?

### ISSUE THREAD

**Issue by Selur** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#6]
Seeing that https://github.com/HolyWu/vs-rife has an option:
'scale: Controls the process resolution for optical flow model. Try scale=0.5 for 4K video. Must be 0.25, 0.5, 1.0, 2.0, or 4.0.'
I was wondering whether this option could be supported here too?
(I prefer this filter since it doesn't require a 5.4GB PyTorch installaiton.)

**Comment by HolyWu** [comment]
Nope. The upstream https://github.com/nihui/rife-ncnn-vulkan only provides an uhd argument, having no adjustable `scale` argument.

**Comment by Selur** [comment]
Okay, thanks. :)

**Comment by Selur** [comment]
btw. would be nice if you also supported the updated models (3.5 and 3.8), see: https://github.com/nihui/rife-ncnn-vulkan/issues/25

**Comment by HolyWu** [comment]
> 
> -> made a request to the upstream project ([nihui/rife-ncnn-vulkan#27](https://github.com/nihui/rife-ncnn-vulkan/issues/27)) ;)

Well, you should point to https://github.com/hzwer/arXiv2020-RIFE/blob/main/inference_video.py#L64 rather than mine repo in your issue, because that functionality comes from the original author of the algorithm.

**Comment by HolyWu** [comment]
> 
> 
> btw. would be nice if you also supported the updated models (3.5 and 3.8), see: [nihui/rife-ncnn-vulkan#25](https://github.com/nihui/rife-ncnn-vulkan/issues/25)

The models cannot be used directly and need to be converted to ncnn's format. Only the author of https://github.com/nihui/rife-ncnn-vulkan can do it.

**Comment by Selur** [comment]
Okay, so I keep fingers crossed that nihui can and will convert them so that they can be added here. :)
