### ISSUE TITLE
Conflict when running multiple instances

### ISSUE THREAD

**Issue by mysteryx93** [HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan#7]
If I run RIFE twice in a script, and open the script multiple times, sometimes I get random junk output from RIFE. Also, the process fails to terminate properly.

Interestingly enough, if RIFE is set only once in the script, neither of these problems occur.

Also for general purposes, model 2.4 gives better output than model 3.1, and according to some, 2.3 gives better output than 2.4. Any chance to have model 2.3 available?

Finally, I have dual-graphics in my laptop. By default it's using the integrated Intel. If I set gpu_id=1, it says invalid GPU id. How can I use the dedicated graphics card?

**Comment by HolyWu** [comment]
> If I run RIFE twice in a script, and open the script multiple times, sometimes I get random junk output from RIFE. Also, the process fails to terminate properly.

What happened when the process failed to terminate properly? Any error message? Or the application just silently crashed?

> Also for general purposes, model 2.4 gives better output than model 3.1, and according to some, 2.3 gives better output than 2.4. Any chance to have model 2.3 available?

Unfortunately, the upstream https://github.com/nihui/rife-ncnn-vulkan/tree/master/models only has model v2.0 and v2.4 but no v2.3, hence I can't make model 2.3 available.

> Finally, I have dual-graphics in my laptop. By default it's using the integrated Intel. If I set gpu_id=1, it says invalid GPU id. How can I use the dedicated graphics card?

Try setting `list_gpu=True` and preview the script. The detected Vulkan devices will be printed on the frame.

**Comment by mysteryx93** [comment]
There is no error message. Everything looks fine. Until I look in the Task Manager and see several unclosed processes.

**Comment by mysteryx93** [comment]
ok I got list_gpu to work. It says NVIDIA=0, Intel=1. If I run with gpu_id=0, NVidia card has 0% usage, and Intel has 3% usage. If I run with gpu_id=1, it says invalid GPU device.

**Comment by mysteryx93** [comment]
btw there are more models available here. Can those be ported?
https://github.com/HolyWu/vs-rife/tree/master/vsrife
